!#PYFT transfo: --checkKeyDim Err

MODULE MOD_CHECK_KO
    IMPLICIT NONE
CONTAINS
    SUBROUTINE PARENT(A)
        REAL, DIMENSION(MERGE(10,0,FLAG)), INTENT(INOUT) :: A
        A = 0
    END SUBROUTINE PARENT
    SUBROUTINE CHILD(A)
        REAL, DIMENSION(MERGE(20,0,OTHER)), INTENT(INOUT) :: A
        A = 0
    END SUBROUTINE CHILD
END MODULE MOD_CHECK_KO
