!#PYFT transfo: --convertuseModuleToIncludes

MODULE M_acchem
CONTAINS
     
!OPTIONS XOPT(NOEVAL)
SUBROUTINE ACCHEM(YPCHEM_ACLIB,YCHEMS,YDCST_ACLIB,&
 &     KIDIA,KFDIA,KLON,KLEV,PTSTEP,PALB,PGEMU,PGELAM,PGAW,PAPRS,PAPRSF,PDELP,PT,PQ,PQLI,PNEB, &
 &     RCODEC,RSIDEC,RCOVSR,RSIVSR,PFCHQ,PQM,&
 &     PTENC, PTO3, PEMIS, PCOTRA, LDCOTRA_CHEM, &
 &     PAREAD_NAT,PAREAD_ICE,PAREAD_SUL)

!**** *ACCHEM*

!     Sujet.
!     ------
!     - CALCUL DE L'EVOLUTION DE LA CONCENTRATION DES ESPECES CHIMIQUES
!     - CALCULATION OF CHEMICAL SPECIES CONCENTRATION

!**   Interface.
!     ----------
!        *CALL* *ACCHEM*

!     Externes.
!     ---------
!         ACCH_SOLA
!         ACCH_RELA
!         ACCH_PHOT
!         ACCH_KRAT
!         ACCH_EQUI
!         ACCH_TEND
!         ACCH_CSRV
!         ACCH_ELEM
!         ACCH_HANA
!         ACCH_HSED
!         ACCH_NEBJ
!         ACCH_LAOA

!     Methode.
!     --------

!     Reference.
!    -----------

!     Auteur.
!    --------
!         10-04, D. Saint-Martin, H. Teyssedre, M. Michou

!     Modifications :
!    ----------------
!         12-03, H. Teyssedre, suppression des CDLOCK
!         12-11, M. Michou, add of chemical diagnostics
!         13-02, M. Michou, deal with different units in H2SO4 forcings
!         15-11, D. StMartin, consider aviation emissions and NOx plume (cf Huszar)
!         16-03, M. Michou optimization and level above which chemistry is not computed
!         16-08, D. StMartin, total ozone column PTO3 as a input
!         16-08, D. StMartin, correction for arrays ZPPART (considering PSC mask)
!         16-11, D. StMartin, correction for gridbox surface area
!         16-11, D. StMartin, introduce CHEM_LSAMECO2 for geo-chemical CO2
!         02-2017, D. StMartin, Diagnostics for XIOS added
!         01-2018, D. StMartin, Diagnostics for XIOS added (oxloss/oxprod)
!         09-2018, M. Michou, routine adapted from ARPEGE-Climat 6.3 to ARPIFS cy 46
!         07-2021, M. Michou, routine adapted to cy48 - concentrations not modified anymore in this routine 
!                             chemical tendencies as output arguments 
!-----------------------------------------------------------------------

USE PARKIND1,   ONLY  : JPIM, JPRB
USE YOMHOOK,    ONLY  : LHOOK, DR_HOOK
USE ARPCLIM_CHEM_MODULE,  ONLY : JPCHEM_NJ, JPCHEM_NKH, JPCHEM_NK,             &
 &                   JPCHEM_NITER_MAX,                                         &
 &                   CHEM_LONLYSTRAT,                                          &
 &                   JPHONO, JPSO2, JPETH, JPALKANEbis, JPALKENEbis, JPISOTOT, &
 &                   JPAROMATIC, JPALD, JPKET, JPMACR, JPONIT, JPPAN, JPOP2,   &
 &                   JPHC8P, JPOLIP, JPISOP, JPPHO, JPTOLP, JPACO3, JPOLNN,    &
 &                   JPXO2,  JPSULF, JPNIGHTNO, JPADDT, JPH2O, JPLIN_AOA,      &
 &                   JPO3P,  JPO1D,  JPO3,      JPN,    JPNO,  JPNO2,          &
 &                   JPNO3,  JPClO,  JPCl,      JPBrO,  JPBr,  JPH,            &
 &                   JPOH,   JPHO2,  JPCH3,     JPCH3O        ,JPNDROP,        &
 &                   JPH2SO4,                                                  &
 &                   JPK_ClONO2_H2O, JPK_ClONO2_HCl, JPK_N2O5_H2O,             &
 &                   JPK_N2O5_HCl, JPK_HOCl_HCl, JPK_BrONO2_H2O, JPK_HOBr_HCl, &
 &                   JPK_HOBr_HBr, JPK_HOCl_HBr,                               &
 &                   CHEM_TSTEP, CHEM_LCHQ, CHEM_LSOLIDP, CHEM_LNEBJ,          &
 &                   CHEM_HPSC_LAT, CHEM_LH2SO4UNIT,                           &
 &                   JPCO2, JPNOx, JPCO2g, CHEM_LSAMECO2, JPOx,                &
 &                   JPN2O, JPCH4, JPCO
!USE YOMCHEMEMIS, ONLY : LCHEM_EMIS3D, JPEMFT, JPEMNOx, JPEMLNOx
!USE YOMCOTRA, ONLY : L_C09, JPTRF, EICO2, MWCO2, EINOx, MWNOx

USE MODD_CST_ACLIB,        ONLY : TCST_ACLIB
USE MODD_PARAM_CHEM_ACLIB, ONLY : TPARAM_CHEM_ACLIB, TCHEM
USE ARPCLIM_CHEM_MODULE,   ONLY : CHEM_AOAMAX

#ifdef WXIOS
USE YOMXIOS            ,   ONLY : LXIOS
#endif WXIOS                                                                                    
USE M_acch_hden, ONLY: ACCH_HDEN
USE M_acch_hete, ONLY: ACCH_HETE
IMPLICIT NONE

! -- ARGUMENTS
TYPE(TPARAM_CHEM_ACLIB)                   , INTENT(IN) :: YPCHEM_ACLIB
TYPE(TCHEM), DIMENSION(YPCHEM_ACLIB%NCHEM), INTENT(IN) :: YCHEMS
TYPE(TCST_ACLIB)                          , INTENT(IN) :: YDCST_ACLIB
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
REAL(KIND=JPRB),    INTENT(IN) :: PTSTEP               ! TIME STEP
REAL(KIND=JPRB), INTENT(IN)    :: PALB(KLON)           ! MODEL SURFACE SHORTWAVE ALBEDO
REAL(KIND=JPRB), INTENT(IN)    :: PGEMU(KLON)          ! SINE OF GEOGRAPHICAL LATITUDE
REAL(KIND=JPRB), INTENT(IN)    :: PGELAM(KLON)         ! GEOGRAPHICAL LONGITUDE
REAL(KIND=JPRB), INTENT(IN)    :: PGAW(KLON)           ! GAUSSIAN WEIGHTS
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV)    ! PRESSURE ON FULL LEVELS
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV)   ! PRESSURE ON HALF-LEVELS.
REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV) 
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV)        ! TEMPERATURE
REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV)        ! SPECIFIC HUMIDITY (mass mixing ratio)
REAL(KIND=JPRB), INTENT(IN)    :: PQLI(KLON,KLEV)      ! 
REAL(KIND=JPRB), INTENT(IN)    :: PNEB(KLON,KLEV)      ! NEBULOSITY
REAL(KIND=JPRB), INTENT(IN)    :: RCODEC               ! COSINE OF THE DECLINATION
REAL(KIND=JPRB), INTENT(IN)    :: RSIDEC               !   SINE OF THE DECLINATION
REAL(KIND=JPRB), INTENT(IN)    :: RCOVSR               ! COSINE OF TRUE SOLAR TIME
REAL(KIND=JPRB), INTENT(IN)    :: RSIVSR               !   SINE OF TRUE SOLAR TIME
REAL(KIND=JPRB), INTENT(OUT)   :: PFCHQ(KLON,0:KLEV)   ! CHEMICAL HUMIDITY FLUX
REAL(KIND=JPRB), INTENT(IN)    :: PQM(KLON,KLEV,YPCHEM_ACLIB%NCHEM)   ! CONCENTRATION OF TRACERS  (mol/mol)
REAL(KIND=JPRB), INTENT(INOUT) :: PTENC(KLON,KLEV,YPCHEM_ACLIB%NCHEM) ! TENDENCY OF CONCENTRATION OF TRACERS (mol/mol s-1)
REAL(KIND=JPRB), INTENT(INOUT) :: PTO3(KLON,KLEV)      ! TOTAL OZONE COLUMN (cm-2)
REAL(KIND=JPRB), INTENT(IN)    :: PEMIS(KLON, KLEV, 3) ! 3D CHEMICAL EMISSIONS (unit : kg / gridbox / month)
!                                                              ! use of fuel emissions only at this stage
REAL(KIND=JPRB), INTENT(INOUT) :: PCOTRA(KLON, KLEV, 3)   ! CONTRAIL TRACERS (unit : volume mixing ratio)
LOGICAL,         INTENT(IN)    :: LDCOTRA_CHEM ! KEY TO ACTIVATE CHEMICAL EFFECTS OF CONTRAILS 
REAL(KIND=JPRB), INTENT(OUT),OPTIONAL :: PAREAD_NAT(KLON,KLEV) ! SURFACE AERA DENSITY OF NAT 
REAL(KIND=JPRB), INTENT(OUT),OPTIONAL :: PAREAD_ICE(KLON,KLEV) ! SURFACE AERA DENSITY OF ICE 
REAL(KIND=JPRB), INTENT(OUT),OPTIONAL :: PAREAD_SUL(KLON,KLEV) ! SURFACE AERA DENSITY OF SULFATE 


! -- LOCAL VARIABLES
INTEGER(KIND=JPIM) :: JLEV, JLON, JS, JITER, JDT, JJ, JK
INTEGER(KIND=JPIM) :: KILEV, KFLEV
REAL(KIND=JPRB)    :: ZHOOK_HANDLE
REAL(KIND=JPRB)    :: ZMU0(KLON)                 ! LOCAL COSINE OF INSTANTANEOUS SOLAR ZENITH ANGLE
REAL(KIND=JPRB)    :: ZDAM(KLON,KLEV)            ! DENSITY OF AIR MOLECULES (molec./cm3)
REAL(KIND=JPRB)    :: ZPDAM(KLON)                ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZPT(KLON)                  ! ASSOCIATED POINTER TO TEMPERATURE
REAL(KIND=JPRB)    :: ZPPAPRSF(KLON)             ! ASSOCIATED POINTER TO PRESSURE
REAL(KIND=JPRB)    :: ZJRAT(KLON,KLEV,JPCHEM_NJ) ! PHOTOLYSIS RATES (SEE JPL-PUBLICATIONS FOR UNITS)
REAL(KIND=JPRB)    :: ZJFACT(KLON,KLEV)          ! PHOTOLYSIS CORRECTION FACTOR DUE TO NEBULOSITY
REAL(KIND=JPRB)    :: ZKRAT(KLON,KLEV,JPCHEM_NK) ! CHEMICAL REACTION RATES (SEE JPL-PUBLICATIONS FOR UNITS)
REAL(KIND=JPRB)    :: ZPKRAT(KLON,JPCHEM_NK)     ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZPHRAT(KLON,JPCHEM_NKH)    ! ASSOCIATED POINTER FOR HETEROGENEOUS REACTIONS

LOGICAL            :: GHOXFAM                    ! .TRUE. IF HOx TREATED AS FAMILY; OTHERWISE, EXPLICIT CALCULATION
LOGICAL            :: GELEM                      ! .TRUE. IF MASS CONSERVATION SHOULD BE APPLIED
LOGICAL            :: LDAY(KLON)                 ! .TRUE. IF DAY; NIGHT IF NOT
LOGICAL            :: L1DAY(KLON)                ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZVSED(KLON,KLEV)           ! POLAR STRATOSPHERIC CLOUD SEDIMENTATION VELOCITY
REAL(KIND=JPRB)    :: ZPVSED(KLON)               ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZPPART_HNO3(KLON)          ! FRACTION OF GASEOUS HNO3 (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPPART_H2O(KLON)           ! FRACTION OF GASEOUS H2O (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPPART_HCl(KLON)           ! FRACTION OF GASEOUS HCl (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPPART_HBr(KLON)           ! FRACTION OF GASEOUS HBr (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPART_HNO3sed(KLON,KLEV)   ! RATIO OF SEDIMENTING HNO3 (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPPART_HNO3sed(KLON)       ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZPART_H2Osed(KLON,KLEV)    ! RATIO OF SEDIMENTING H2O (BETWEEN 0 AND 1)
REAL(KIND=JPRB)    :: ZPPART_H2Osed(KLON)        ! ASSOCIATED POINTER
REAL(KIND=JPRB)    :: ZPROD(KLON,YPCHEM_ACLIB%NCHEM)         ! CHEMICAL TENDENCY FOR PRODUCTION
REAL(KIND=JPRB)    :: ZLOSS(KLON,YPCHEM_ACLIB%NCHEM)         ! CHEMICAL TENDENCY FOR DESTRUCTION
REAL(KIND=JPRB)    :: ZQM(KLON,KLEV,YPCHEM_ACLIB%NCHEM)      ! 
REAL(KIND=JPRB)    :: ZPQM(KLON,YPCHEM_ACLIB%NCHEM)          ! TRACER CONCENTRATION AT MODEL LEVEL
REAL(KIND=JPRB)    :: ZPQM0(KLON,YPCHEM_ACLIB%NCHEM)         ! TRACER CONCENTRATION AT MODEL LEVEL (backup) 
REAL(KIND=JPRB)    :: ZPEMIS(KLON, 3)            ! TEMPORARY ARRAY FOR 3D CHEMICAL EMISSIONS
!REAL(KIND=JPRB)    :: ZPCOTRA(KLON, 3)           ! TEMPORARY ARRAY FOR CONTRAIL TRACERS
INTEGER(KIND=JPIM) :: IDT(KLEV)                  ! NUMBER OF SUB TIME STEPS FOR CURRENT LEVEL
REAL(KIND=JPRB)    :: ZSUBTSTEP                  ! SUB-TIMESTEP (s)
INTEGER(KIND=JPIM) :: ITER                       ! NUMBER OF ITERATIONS FOR CHEMICAL SOLVER
REAL(KIND=JPRB)    :: PQ0(KLON,KLEV)             ! INITIAL VALUE OF WATER VAPOR (volume mixing ratio)
REAL(KIND=JPRB)    :: PQ1(KLON,KLEV)             ! FINAL VALUE OF WATER VAPOR (volume mixing ratio)
REAL(KIND=JPRB)    :: ZTENQ(KLON,KLEV)           ! SPECIFIC HUMIDITY TENDENCY
REAL(KIND=JPRB)    :: ZMASKPSC(KLON,KLEV)        ! PSC MASK
REAL(KIND=JPRB)    :: ZMASKSSU(KLON,KLEV)        ! STRATOSPHERIC SULFATE MASK
REAL(KIND=JPRB)    :: ZAREAD_NAT(KLON)           ! ASSOCIATED POINTER TO PAREAD_NAT
REAL(KIND=JPRB)    :: ZAREAD_ICE(KLON)           ! ASSOCIATED POINTER TO PAREAD_ICE
REAL(KIND=JPRB)    :: ZAREAD_SUL(KLON)           ! ASSOCIATED POINTER TO PAREAD_SUL
REAL(KIND=JPRB)    :: ZRGI, ZDT, ZDCH2O
REAL(KIND=JPRB)    :: ZCO2G0(KLON,KLEV)          ! INITIAL VALUE OF GEO-CHEMICAL CO2 (volume mixing ratio)

REAL(KIND=JPRB)    :: ZDALT, ZSURF, ZFACT, ZINVE
REAL(KIND=JPRB)    :: ZEAFT(KLON,KLEV)
REAL(KIND=JPRB)    :: ZEANOx(KLON,KLEV)

REAL(KIND=JPRB)    :: ZO3LOSS(KLON,KLEV), ZO3PROD(KLON,KLEV) ! CHEM. LOSS AND PROD. OF O3 
REAL(KIND=JPRB)    :: ZOxLOSS(KLON,KLEV), ZOxPROD(KLON,KLEV) ! CHEM. LOSS AND PROD. OF Ox 
REAL(KIND=JPRB)    :: ZLOSSN2O(KLON,KLEV), ZLOSSCH4(KLON,KLEV), ZLOSSCO(KLON,KLEV) ! CHEM. LOSS OF N2O, CH4, CO
REAL(KIND=JPRB)    :: ZMAXAOA(KLON,KLEV), ZAOA(KLON,KLEV)    ! AOA ARRAYS
REAL(KIND=JPRB)    :: ZKGM2MOLECM2, ZRMV2RMM, ZDPSUP, ZDPINF

!-- CHECK RELIABILITY OF INPUT ARGUMENTS.
#include "acch_csrv.intfb.h"
#include "acch_elem.intfb.h"
#include "acch_equi.intfb.h"
#include "acch_hana.intfb.h"
#include "acch_hsed.intfb.h"
#include "acch_krat.intfb.h"
#include "acch_laoa.intfb.h"
#include "acch_nebj.intfb.h"
#include "acch_phot.intfb.h"
#include "acch_rela.intfb.h"
#include "acch_sola.intfb.h"
#include "acch_tend.intfb.h"
IF (LHOOK) CALL DR_HOOK('ACCHEM',0,ZHOOK_HANDLE)

ASSOCIATE(NCHEM=>YPCHEM_ACLIB%NCHEM)
ASSOCIATE(NBOT_HPSC=>YPCHEM_ACLIB%NBOT_HPSC, NTOP_HPSC=>YPCHEM_ACLIB%NTOP_HPSC, &
 & NBOT_HOXF=>YPCHEM_ACLIB%NBOT_HOXF, NTOP_ELEM=>YPCHEM_ACLIB%NTOP_ELEM, & 
 & NIV_RELA=>YPCHEM_ACLIB%NIV_RELA, NIV_NO_CHEM=>YPCHEM_ACLIB%NIV_NO_CHEM)
ASSOCIATE(NSTADD=>YPCHEM_ACLIB%NSTADD)

! The local ZQM array will be modified by the chemical scheme
DO JS=1,NCHEM
   DO JLEV=1,KLEV
       ZQM(KIDIA:KFDIA,JLEV,JS)=PQM(KIDIA:KFDIA,JLEV,JS)
   ENDDO
ENDDO


!-- AGE OF AIR CALCULATION
CALL ACCH_LAOA(YDCST_ACLIB,KIDIA,KFDIA,KLON,KLEV,NSTADD,PGEMU,PAPRSF,ZQM(:,:,JPLIN_AOA))
ZMAXAOA(KIDIA:KFDIA,:) = CHEM_AOAMAX
ZAOA(KIDIA:KFDIA,:) = ZMAXAOA(KIDIA:KFDIA,:)-ZQM(KIDIA:KFDIA,:,JPLIN_AOA)

#ifdef WXIOS
IF(LXIOS)THEN !.AND.(.NOT.CHEM_LPERTLINOZO)) THEN
  CALL XSEND('LIN_AOA',PFIELD2=ZAOA(KIDIA:KFDIA,:))
ENDIF
#endif WXIOS

!-- COMPUTE TOTAL OZONE COLUMN PTO3 (in moleculesO3.cm-2)
ZKGM2MOLECM2 = 1.0_JPRB / 7.85151E-22_JPRB
ZRMV2RMM = YDCST_ACLIB%RMO3 / YDCST_ACLIB%RMDG
DO JLON=KIDIA,KFDIA
   ZDPSUP = PAPRSF(JLON,1)
   PTO3(JLON,1) = ZDPSUP*MAX(1.E-11_JPRB, ZQM(JLON,1,JPO3))*ZRMV2RMM*ZKGM2MOLECM2/YDCST_ACLIB%RG
ENDDO
DO JLEV=2,KLEV
   DO JLON=KIDIA,KFDIA
        ZDPSUP = PAPRSF(JLON,JLEV)-PAPRS(JLON,JLEV-1)
        ZDPINF = PAPRS(JLON,JLEV-1)-PAPRSF(JLON,JLEV-1)
        PTO3(JLON,JLEV) = PTO3(JLON,JLEV-1) + &
       & ( ZDPSUP*MAX(1.E-11_JPRB, ZQM(JLON,JLEV,JPO3)) + &
       &   ZDPINF*MAX(1.E-11_JPRB, ZQM(JLON,JLEV-1,JPO3)) )*ZRMV2RMM*ZKGM2MOLECM2/YDCST_ACLIB%RG
    ENDDO
ENDDO


!-- RELAXATION FOR SOURCE SPECIES
call ACCH_RELA(KIDIA,KFDIA,KLON,KLEV,PTSTEP,NCHEM,PAPRSF,ZQM,NIV_RELA)

!-- Initialisation
DO JLEV=0,KLEV
    PFCHQ(KIDIA:KFDIA,JLEV) = 0.0_JPRB
ENDDO

DO JLEV=1,KLEV
    ZTENQ(KIDIA:KFDIA,JLEV) = 0.0_JPRB
    PQ0(KIDIA:KFDIA,JLEV) = 0.0_JPRB
    PQ1(KIDIA:KFDIA,JLEV) = 0.0_JPRB
ENDDO

!-- COMPUTE SOLAR ZENITH ANGLE AND LENGHT OF CURRENT MONTH
call ACCH_SOLA(KIDIA,KFDIA,KLON,PGEMU,PGELAM,RCODEC,RSIDEC,RCOVSR,RSIVSR,ZMU0)

!-- COMPUTE DENSITY OF AIR MOLECULES (molec./cm3)
! NB: 1.38e-17 = k_B (Boltzmann constant) * 1e-6 (for cm3)
DO JLEV=1,KLEV
    ZDAM(KIDIA:KFDIA,JLEV) = PAPRSF(KIDIA:KFDIA,JLEV)/(PT(KIDIA:KFDIA,JLEV)*1.38e-17)
ENDDO

!-- INITIAL VALUE OF GEO-CHEMICAL CO2
DO JLEV=1,KLEV
  ZCO2G0(KIDIA:KFDIA,JLEV) = ZQM(KIDIA:KFDIA,JLEV,JPCO2g)
ENDDO

!-- ARPEGE SPECIFIC HUMIDITY PASSED TO CHEMISTRY
DO JLEV=1,KLEV
    PQ0(KIDIA:KFDIA,JLEV) = MAX(1.E-10_JPRB, PQ(KIDIA:KFDIA,JLEV))
    ZQM(KIDIA:KFDIA,JLEV,JPH2O) = MAX(1.E-10_JPRB, (PQ(KIDIA:KFDIA,JLEV) / (1.-PQ(KIDIA:KFDIA,JLEV))))&
                                & * YDCST_ACLIB%RMDG / YDCST_ACLIB%RMVG
ENDDO

call ACCH_PHOT(YDCST_ACLIB,KIDIA,KFDIA,KLON,KLEV,ZMU0,PALB,PAPRSF,PTO3,ZJRAT,LDAY)

IF (CHEM_LNEBJ) THEN
  call ACCH_NEBJ(KIDIA,KFDIA,KLON,KLEV,ZMU0,PAPRS,PQLI,PNEB,ZJFACT)
  DO JJ=1,JPCHEM_NJ
  DO JLEV=1,KLEV
    ZJRAT(KIDIA:KFDIA,JLEV,JJ)=ZJFACT(KIDIA:KFDIA,JLEV)*ZJRAT(KIDIA:KFDIA,JLEV,JJ)
  ENDDO
  ENDDO
ENDIF

call ACCH_KRAT(KIDIA,KFDIA,KLON,KLEV,ZDAM,PT,ZJRAT,ZKRAT)

ZPPART_HNO3(:) = 1.0
ZPPART_H2O(:)  = 1.0
ZPPART_HCl(:)  = 1.0
ZPPART_HBr(:)  = 1.0
ZPART_HNO3sed(:,:)= 0.0
ZPART_H2Osed(:,:) = 0.0

KILEV=1
KFLEV=KLEV

! NUMBER OF CHEMICAL SUB-TIMESTEPS ASSOCIATED TO EACH VERTICAL LEVEL
IDT(:)=0_JPIM
  DO JLEV=KILEV,KFLEV
  ZDT = PTSTEP / CHEM_TSTEP(JLEV)
    IF (ZDT-INT(ZDT) > 0.0_JPRB) THEN
      IDT(JLEV)=INT(ZDT)+1_JPIM
    ELSE
      IDT(JLEV)=MAX(1_JPIM, INT(ZDT))
    ENDIF
  ENDDO
  IF (CHEM_LONLYSTRAT) THEN
    DO JLEV=NIV_RELA,KLEV
      IDT(JLEV)=0
    ENDDO
  ENDIF
  DO JLEV=KILEV, NIV_NO_CHEM
      IDT(JLEV)=0
  ENDDO

! MASKS FOR : POLAR STRASTOPHERIC CLOUD (PSC)
!             STRATOSPHERIC SULFATE (SSU)
ZMASKPSC(:,:)=0.0_JPRB
ZMASKSSU(:,:)=0.0_JPRB

DO JLEV=NTOP_HPSC,NBOT_HPSC
  DO JLON = KIDIA, KFDIA
    IF (ASIN(PGEMU(JLON))*180._JPRB/YDCST_ACLIB%RPI >= CHEM_HPSC_LAT) THEN
      ZMASKPSC(JLON,JLEV) = 1.0_JPRB  ! POLAR STRATOSPHERIC CLOUD MASK
      ZMASKSSU(JLON,JLEV) = 1.0_JPRB  ! STRATOSPHERIC SULFATE MASK
    ENDIF
    IF (ASIN(PGEMU(JLON))*180._JPRB/YDCST_ACLIB%RPI <= -CHEM_HPSC_LAT) THEN
      ZMASKPSC(JLON,JLEV) = 1.0_JPRB  ! POLAR STRATOSPHERIC CLOUD MASK
      ZMASKSSU(JLON,JLEV) = 1.0_JPRB  ! STRATOSPHERIC SULFATE MASK
    ENDIF
  ENDDO
!  DO JLON = KIDIA, KFDIA
!    ZMASKSSU(JLON,JLEV) = 1.0_JPRB  ! STRATOSPHERIC SULFATE MASK
!  ENDDO
ENDDO
!===================================================================================================================    
!-------------------------------------------------------------
!----------   conversion of aviation emissions      ----------
!----------  from kg/gridbox/month to kg/m3/month       ----------
!  To be added later
!-------------------------------------------------------------
!IF (LCHEM_EMIS3D) THEN
  ! number of seconds per month = 30.4375*24*60*60 = 2629800 s  
  ! conversion m**3 c**3
  ! Quantify and IMPACT emissions kg gridbox-1 month-1 
  !ZFACT = 1.0D-06 / 2629800.0
  !DO JLON=KIDIA,KFDIA
    !ZSURF = 4.0*YDCST_ACLIB%RPI*RA*RA*PGAW(JLON)
    !DO JLEV=1,KLEV
      !ZDALT = RD*PDELP(JLON,JLEV)*PT(JLON,JLEV)/(PAPRSF(JLON,JLEV)*YDCST_ACLIB%RG)
      !ZINVE = 1.0 / (ZSURF*ZDALT)
      ! kg/gridbox/month ---> kg/m**3/month
      !ZEAFT(JLON,JLEV)  = ZINVE * PEMIS(JLON, JLEV, JPEMFT)
      !ZEANOx(JLON,JLEV) = ZINVE * PEMIS(JLON, JLEV, JPEMNOx)
      ! kg/m**3/month ---> kg/cm**3/s 
      !ZEAFT(JLON,JLEV)  = ZFACT * ZEAFT(JLON,JLEV)
      !ZEANOx(JLON,JLEV) = ZFACT * ZEANOx(JLON,JLEV)
    !ENDDO
   !ENDDO
   !CALL ABOR1('aviation emissions in acchem: How did we get here?')
!ENDIF
!===================================================================================================================    

DO JLEV=KILEV,KFLEV

  IF (JLEV <= NBOT_HOXF) THEN
    GHOXFAM=.TRUE.
  ELSE
    GHOXFAM=.FALSE.
  ENDIF
  IF (JLEV >= NTOP_ELEM) THEN
    GELEM=.TRUE.
  ELSE
    GELEM=.FALSE.
  ENDIF

!-- CONVERT MIXING RATIOS (mol/mol) TO DENSITIES (molec/cm3)
!   convert from kg/kg TO DENSITIES (molec/cm3): needs to be implemented 
  DO JS=1,NCHEM
    IF (JS /= JPNDROP) THEN
        ZPQM(KIDIA:KFDIA,JS) = MAX(ZQM(KIDIA:KFDIA,JLEV,JS), 1.d-30)*ZDAM(KIDIA:KFDIA,JLEV)
    ENDIF
  ENDDO
!  IF (LDCOTRA_CHEM) THEN 
!      ZPCOTRA(KIDIA:KFDIA, JPTRF) = PCOTRA(KIDIA:KFDIA, JLEV, JPTRF) ! traceur fuel unit : g fuel / cm-3
!  ENDIF
  IF (CHEM_LSOLIDP) THEN
      ZPQM(KIDIA:KFDIA,JPNDROP) = ZQM(KIDIA:KFDIA,JLEV,JPNDROP)
  ENDIF
  IF (CHEM_LH2SO4UNIT) THEN  ! H2SO4 provided in molec/cm3 air
      ZPQM(KIDIA:KFDIA,JPH2SO4) = ZQM(KIDIA:KFDIA,JLEV,JPH2SO4)
  ENDIF
  !IF (LCHEM_EMIS3D) THEN
  !  ZPEMIS(KIDIA:KFDIA, JPEMFT)   = ZEAFT(KIDIA:KFDIA, JLEV)
  !  ZPEMIS(KIDIA:KFDIA, JPEMNOx)  = ZEANOx(KIDIA:KFDIA, JLEV)
  !  ZPEMIS(KIDIA:KFDIA, JPEMLNOx) = PEMIS(KIDIA:KFDIA, JLEV, JPEMLNOx)
  !ELSE
  !  ZPEMIS(KIDIA:KFDIA, :) = 0.0_JPRB
  !ENDIF
  IF (CHEM_LONLYSTRAT) THEN
      ZPQM(KIDIA:KFDIA,JPHONO)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPSO2)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPETH)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPALKANEbis)=  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPALKENEbis)=  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPISOTOT)   =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPAROMATIC) =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPALD)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPKET)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPMACR)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPONIT)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPPAN)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPOP2)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPHC8P)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPOLIP)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPISOP)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPPHO)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPTOLP)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPACO3)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPOLNN)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPXO2)      =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPSULF)     =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPNIGHTNO)  =  0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPADDT)     =  0.0_JPRB
  ENDIF

! CHEMICAL SUB-TIMESTEP DEPENDS ON VERTICAL LEVEL
  IF (IDT(JLEV) > 0) THEN
    ZSUBTSTEP=PTSTEP/REAL(IDT(JLEV))
    ZPPART_HNO3sed(:) = 0.0_JPRB
    ZPPART_H2Osed (:) = 0.0_JPRB
    ZPHRAT(:,:) = 0.0_JPRB
    ZPVSED(:) = 0.0_JPRB
    ZAREAD_NAT(:) = 0.0_JPRB
    ZAREAD_ICE(:) = 0.0_JPRB
    ZAREAD_SUL(:) = 0.0_JPRB
    ITER=JPCHEM_NITER_MAX
    L1DAY      (KIDIA:KFDIA) = LDAY      (KIDIA:KFDIA)
    ZPDAM      (KIDIA:KFDIA) = ZDAM      (KIDIA:KFDIA,JLEV)
    ZPT        (KIDIA:KFDIA) = PT        (KIDIA:KFDIA,JLEV)
    ZPPAPRSF   (KIDIA:KFDIA) = PAPRSF    (KIDIA:KFDIA,JLEV)
    DO JK=1,JPCHEM_NK
      ZPKRAT(KIDIA:KFDIA,JK) = ZKRAT(KIDIA:KFDIA,JLEV,JK)
    ENDDO

    IF (CHEM_LSOLIDP) THEN
       IF ((JLEV >= NTOP_HPSC) .AND. (JLEV <= NBOT_HPSC)) THEN
          call ACCH_HANA(YDCST_ACLIB,KIDIA,KFDIA,KLON,NCHEM,ZPT,ZPPAPRSF,ZPDAM,ZPQM,ZPVSED,ZPHRAT,    &
 &                            ZPPART_HNO3,ZPPART_H2O,ZPPART_HCl,ZPPART_HBr,        &
 &                            ZPPART_HNO3sed,ZPPART_H2Osed,ZAREAD_NAT,ZAREAD_ICE,ZAREAD_SUL)

          ZPKRAT(KIDIA:KFDIA,JPK_ClONO2_H2O)=ZPHRAT(KIDIA:KFDIA,1)*ZMASKSSU(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_ClONO2_HCl)=ZPHRAT(KIDIA:KFDIA,2)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_N2O5_H2O  )=ZPHRAT(KIDIA:KFDIA,3)*ZMASKSSU(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_N2O5_HCl  )=ZPHRAT(KIDIA:KFDIA,4)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_HOCl_HCl  )=ZPHRAT(KIDIA:KFDIA,5)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_BrONO2_H2O)=ZPHRAT(KIDIA:KFDIA,6)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_HOBr_HCl  )=ZPHRAT(KIDIA:KFDIA,7)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_HOBr_HBr  )=ZPHRAT(KIDIA:KFDIA,8)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPKRAT(KIDIA:KFDIA,JPK_HOCl_HBr  )=ZPHRAT(KIDIA:KFDIA,9)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPPART_HNO3(KIDIA:KFDIA)=MAX(1._JPRB-ZMASKPSC(KIDIA:KFDIA,JLEV),ZPPART_HNO3(KIDIA:KFDIA))
          ZPPART_H2O(KIDIA:KFDIA) =MAX(1._JPRB-ZMASKPSC(KIDIA:KFDIA,JLEV),ZPPART_H2O(KIDIA:KFDIA))
          ZPPART_HCl(KIDIA:KFDIA) =MAX(1._JPRB-ZMASKPSC(KIDIA:KFDIA,JLEV),ZPPART_HCl(KIDIA:KFDIA))
          ZPPART_HBr(KIDIA:KFDIA) =MAX(1._JPRB-ZMASKPSC(KIDIA:KFDIA,JLEV),ZPPART_HBr(KIDIA:KFDIA))
          ZPART_HNO3sed(KIDIA:KFDIA,JLEV)=(1._JPRB-ZPPART_HNO3sed(KIDIA:KFDIA))*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZPART_H2Osed (KIDIA:KFDIA,JLEV)=(1._JPRB-ZPPART_H2Osed (KIDIA:KFDIA))*ZMASKPSC(KIDIA:KFDIA,JLEV)
          ZVSED      (KIDIA:KFDIA,JLEV)=ZPVSED(KIDIA:KFDIA)*ZMASKPSC(KIDIA:KFDIA,JLEV)
          PAREAD_NAT(KIDIA:KFDIA,JLEV)=ZAREAD_NAT(KIDIA:KFDIA)
          PAREAD_ICE(KIDIA:KFDIA,JLEV)=ZAREAD_ICE(KIDIA:KFDIA)
          PAREAD_SUL(KIDIA:KFDIA,JLEV)=ZAREAD_SUL(KIDIA:KFDIA)
      ENDIF
    ENDIF

    DO JDT=1,IDT(JLEV)

!===================================================================================================================    
      !IF (LDCOTRA_CHEM) THEN
      ! To be added later ; routines will be reviewed to return tendencies and not modified concentrations
        ! for coherence with the rest of the code
        ! To convert emissions from kgfuel.cm-3.s-1 to molec.cm-3.s-1
        ! ZPEMIS(:, JPEMFT) in kgfuel.cm-3.s-1
        ! EICO2             in gCO2.kgfuel-1
        ! MWCO2             in gCO2.mol-1
        ! RAVOG            in molec CO2.mol-1

        ! [CO_2] : DIRECT EFFECT FROM AVIATION EMISSIONS
        !DO JLON = KIDIA, KFDIA
        !  ZPQM(JLON, JPCO2) = ZPQM(JLON, JPCO2) + ZPEMIS(JLON, JPEMFT)*EICO2/MWCO2*YDCST_ACLIB%RAVOG*ZSUBTSTEP
        !ENDDO

        ! [NO_x] and [O_3]
        ! PLUME EFFECT (L_C09 = .TRUE.)
        ! OR DIRECT EFFECT FROM AVIATION EMISSIONS (BASIC CASE IN C09) 
        !IF (L_C09) THEN
        !  CALL ACCH_NOXP(KIDIA, KFDIA, KLON, ZPDAM, ZSUBTSTEP, L1DAY, ZPEMIS, ZPQM, ZPCOTRA)            
        !ELSE
        !  DO JLON = KIDIA, KFDIA
        !    ZPQM(JLON, JPNOx) = ZPQM(JLON, JPNOx) + ZPEMIS(JLON, JPEMFT)*EINOx/MWNOx*YDCST_ACLIB%RAVOG*ZSUBTSTEP
        !  ENDDO  
        !ENDIF
         !CALL ABOR1('Contrail parameterisation: How did we get here?')
      !ENDIF
!===================================================================================================================    

      DO JS=1,NCHEM
          ZPQM0(KIDIA:KFDIA,JS) = ZPQM(KIDIA:KFDIA,JS)
      ENDDO
      DO JITER=1,ITER
        call ACCH_EQUI(KIDIA,KFDIA,KLON,NCHEM,ZPDAM,ZPKRAT,L1DAY,GHOxFAM,ZPPART_HNO3, &
 &                     ZPPART_H2O,ZPPART_HCl,ZPPART_HBr,ZPQM)
        call ACCH_TEND(KIDIA,KFDIA,KLON,NCHEM,ZPDAM,ZPKRAT,ZPQM,L1DAY,ZPPART_HNO3, &
 &                     ZPPART_H2O,ZPPART_HCl,ZPPART_HBr,ZPROD,ZLOSS)
!       -- SEMI-IMPLICIT SOLVER
!       NB: Compute var(t+1), knowing var0(t-1) and production and first order destruction rates
        DO JS=1,NCHEM
          IF ((YCHEMS(JS)%LADV).AND.(JS /= JPLIN_AOA)) THEN
              ZPQM(KIDIA:KFDIA,JS) = MAX((ZPQM0(KIDIA:KFDIA,JS)+ZSUBTSTEP*ZPROD(KIDIA:KFDIA,JS))/ &
 &            (1.+ZSUBTSTEP*ZLOSS(KIDIA:KFDIA,JS)), 1.d-10)
          ENDIF
        ENDDO ! END OF LOOP UPON CHEMICAL SPECIES
        IF (GELEM) call ACCH_ELEM(KIDIA,KFDIA,KLON,NCHEM,ZPQM0,ZPQM)
      ENDDO ! END OF LOOP UPON ITERATIONS
    ENDDO ! END OF LOOP UPON SUB-CHEMICAL TIMESTEP
  ELSE ! CONDITION UPON TIMESTEP
      ZPQM(KIDIA:KFDIA,JPO3P ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPO1D ) = 0.0_JPRB
!      ZPQM(KIDIA:KFDIA,JPO3  ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPN   ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPNO  ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPNO2 ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPNO3 ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPClO ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPCl  ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPBrO ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPBr  ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPH   ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPOH  ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPHO2 ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPCH3 ) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPCH3O) = 0.0_JPRB
      ZPQM(KIDIA:KFDIA,JPADDT) = 0.0_JPRB
  ENDIF ! END OF CONDITION UPON TIMESTEP

! RATES OF PRODUCTION AND DESTRUCTION OF O3 mol m-3 s-1
  ZO3LOSS(KIDIA:KFDIA,JLEV) = ZLOSS(KIDIA:KFDIA,JPOx)*ZPQM(KIDIA:KFDIA,JPOx)*  &
&              ((ZPQM(KIDIA:KFDIA,JPO3)/ZPQM(KIDIA:KFDIA,JPOx)))*1e6/YDCST_ACLIB%RAVOG
  ZO3PROD(KIDIA:KFDIA,JLEV) = ZPROD(KIDIA:KFDIA,JPOx)*  &
&              ((ZPQM(KIDIA:KFDIA,JPO3)/ZPQM(KIDIA:KFDIA,JPOx)))*1e6/YDCST_ACLIB%RAVOG    

! RATES OF PRODUCTION AND DESTRUCTION OF Ox mol m-3 s-1
  ZOxLOSS(KIDIA:KFDIA,JLEV) = ZLOSS(KIDIA:KFDIA,JPOx)*ZPQM(KIDIA:KFDIA,JPOx)*1e6/YDCST_ACLIB%RAVOG
  ZOxPROD(KIDIA:KFDIA,JLEV) = ZPROD(KIDIA:KFDIA,JPOx)*1e6/YDCST_ACLIB%RAVOG    

! RATES OF DESTRUCTION OF N2O CH4 AND CO mol m-3 s-1
  ZLOSSN2O(KIDIA:KFDIA,JLEV) = ZLOSS(KIDIA:KFDIA,JPN2O)*ZPQM(KIDIA:KFDIA,JPN2O)*1e6/YDCST_ACLIB%RAVOG
  ZLOSSCH4(KIDIA:KFDIA,JLEV) = ZLOSS(KIDIA:KFDIA,JPCH4)*ZPQM(KIDIA:KFDIA,JPCH4)*1e6/YDCST_ACLIB%RAVOG
  ZLOSSCO(KIDIA:KFDIA,JLEV)  = ZLOSS(KIDIA:KFDIA,JPCO)*ZPQM(KIDIA:KFDIA,JPCO)*1e6/YDCST_ACLIB%RAVOG

!-- CONVERT BACK TO VOLUMIC MIXING (mol/mol) RATIOS AND BUILD 3D ARRAYS
!-- CONVERT BACK TO MASS MIXING (kg/kg) RATIOS AND BUILD 3D ARRAYS : to be implemented later
  DO JS=1,NCHEM
    IF (JS /= JPNDROP) THEN
        ZQM(KIDIA:KFDIA,JLEV,JS) = MAX(ZPQM(KIDIA:KFDIA,JS)/ZDAM(KIDIA:KFDIA,JLEV),1.d-30)
    ENDIF
  ENDDO
  IF (CHEM_LSOLIDP) THEN
        ZQM(KIDIA:KFDIA,JLEV,JPNDROP) = ZPQM(KIDIA:KFDIA,JPNDROP)
  ENDIF
  IF (CHEM_LH2SO4UNIT) THEN  ! H2SO4 provided in molec/cm3 air
      ZQM(KIDIA:KFDIA,JLEV,JPH2SO4) = ZPQM(KIDIA:KFDIA,JPH2SO4)
  ENDIF
!  IF (LDCOTRA_CHEM) THEN
!      PCOTRA(KIDIA:KFDIA, JLEV, JPTRF) = ZPCOTRA(KIDIA:KFDIA, JPTRF)
!  ENDIF
  IF (.NOT. CHEM_LSAMECO2) THEN
  ! in this case, geo-chemical CO2 is not modified by chemical reactions
    ZQM(KIDIA:KFDIA,JLEV,JPCO2g) = ZCO2G0(KIDIA:KFDIA,JLEV)
  ENDIF
ENDDO ! END OF LOOP UPON VERTICAL LEVELS


#ifdef WXIOS
IF (LXIOS) THEN
  CALL XSEND('o3loss',  PFIELD2=ZO3LOSS(KIDIA:KFDIA,:))
  CALL XSEND('o3prod',  PFIELD2=ZO3PROD(KIDIA:KFDIA,:))
  CALL XSEND('oxloss',  PFIELD2=ZOxLOSS(KIDIA:KFDIA,:))
  CALL XSEND('oxprod',  PFIELD2=ZOxPROD(KIDIA:KFDIA,:))
  CALL XSEND('lossn2o', PFIELD2=ZLOSSN2O(KIDIA:KFDIA,:))
  CALL XSEND('lossch4', PFIELD2=ZLOSSCH4(KIDIA:KFDIA,:))
  CALL XSEND('lossco',  PFIELD2=ZLOSSCO(KIDIA:KFDIA,:))
ENDIF
#endif WXIOS

! A constant vertical profile is imposed at first levels in the mesosphere
DO JS=1,NCHEM
   DO JLEV=1,NIV_NO_CHEM
     DO JLON=KIDIA,KFDIA
       ZQM(JLON,JLEV,JS)=ZQM(JLON,NIV_NO_CHEM+1,JS)
     ENDDO
   ENDDO
ENDDO


!--- STRATOSPHERIC PSC SEDIMENTATION
IF (CHEM_LSOLIDP) THEN
  call ACCH_HSED(YDCST_ACLIB,KIDIA,KFDIA,KLON,KLEV,NCHEM,PTSTEP,PAPRSF,PAPRS,PT,ZMASKPSC,ZVSED,ZPART_HNO3sed,ZPART_H2Osed,ZQM)
ENDIF

!-- CALCUL DE LA TENDANCE DE Q
IF (CHEM_LCHQ) THEN
  DO JLEV=1,KLEV
      PQ1(KIDIA:KFDIA,JLEV) = MAX(1.E-10_JPRB, ( ZQM(KIDIA:KFDIA,JLEV,JPH2O) * YDCST_ACLIB%RMVG / YDCST_ACLIB%RMDG ) /  &
 &                     ( 1.+ZQM(KIDIA:KFDIA,JLEV,JPH2O) * YDCST_ACLIB%RMVG / YDCST_ACLIB%RMDG ) )
      ZTENQ(KIDIA:KFDIA,JLEV) = (PQ1(KIDIA:KFDIA,JLEV) - PQ0(KIDIA:KFDIA,JLEV))/PTSTEP
  ENDDO
ENDIF

!-- CALCUL DU FLUX DE VAPEUR D'EAU, PAR INTEGRATION DE LA TENDANCE DE BAS EN HAUT
ZRGI = 1.0_JPRB/YDCST_ACLIB%RG
DO JLEV=KLEV,1,-1
    PFCHQ(KIDIA:KFDIA,JLEV-1) = PFCHQ(KIDIA:KFDIA,JLEV) + ZRGI*ZTENQ(KIDIA:KFDIA,JLEV)*PDELP(KIDIA:KFDIA,JLEV)
ENDDO

call ACCH_CSRV(KIDIA,KFDIA,KLON,KLEV,NCHEM,ZQM)

!-- CALCUL DES TENDANCES DUES AU SCHEMA CHIMIQUE 
DO JS=1,NCHEM
   DO JLEV=1,KLEV
      PTENC(KIDIA:KFDIA,JLEV,JS) = (ZQM(KIDIA:KFDIA,JLEV,JS) - PQM(KIDIA:KFDIA,JLEV,JS)) / PTSTEP
   ENDDO
ENDDO

END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('ACCHEM',1,ZHOOK_HANDLE)

END SUBROUTINE ACCHEM
END MODULE M_acchem
