MODULE TOTO
  REAL :: X_TOTO
  INTERFACE I_TOTO
    MODULE PROCEDURE S_TOTO
  END INTERFACE
  CONTAINS
  SUBROUTINE S_TOTO(X)
    REAL, INTENT(IN) :: X
    PRINT*, X
  END SUBROUTINE S_TOTO
  FUNCTION F_TOTO(I)
    REAL :: I, F_TOTO
    F_TOTO = I + 1.
  END FUNCTION F_TOTO
  SUBROUTINE S2_TOTO(X)
    REAL, INTENT(IN) :: X
    PRINT*, X
    CONTAINS
      SUBROUTINE S3_TOTO
      END SUBROUTINE S3_TOTO
  END SUBROUTINE S2_TOTO
END MODULE TOTO

MODULE TOTO2
  REAL :: X_TOTO2
END MODULE TOTO2
